version: '3.1'

services:

  mysql-dev:
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
    ports:
      - 3307:3307
    volumes:
    - ./mysql-dump:/docker-entrypoint-initdb.d